### ISSUE TITLE
upgrade failed from version 3.3 to 4.5.5 with agave-validator: not found

### ISSUE THREAD

**Issue by fbettag** [EpicsDAO/solv#249]
Hey there,

the upgrade procedure failed for me. i've been running version 3.3 for a while now and just tried to upgrade to 4.5.5.

After the upgrade i keep getting this:
$ solv restart
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
/bin/sh: 1: agave-validator: not found

**Comment by POPPIN-FUMI** [comment]
You can reinstall it again!
Please backup all the data before do it!

**Comment by fbettag** [comment]
thank you. that worked! now my question is, where do i find the validator pubkey?

i've been operating a testnet node for a few months now with solv (now successfully updated), but i was wondering if i had to load the bytes from testnet-validator-keypair.json myself to get a pubkey?
